---

- name: Set docker-pgp repo key (ubuntu)
  ansible.builtin.copy:
    src:  ubuntu-pgp
    dest: /tmp
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Set docker-pgp repo key (centos)
  ansible.builtin.copy:
    src:  centos-pgp
    dest: /tmp
    owner: root
    group: root
    mode: '0600'
  when: ansible_facts['distribution'] == "CentOS"

- name: Import docker-pgp repo key (CentOS)
  ansible.builtin.rpm_key:
    state: present
    key: /tmp/centos-pgp
  when: ansible_facts['distribution'] == "CentOS"

- name: Import docker-pgp repo key (Ubuntu)
  ansible.builtin.apt_key:
    file: /tmp/ubuntu-pgp
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add repository (CentOS)
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    gpgcheck: yes
    state: present
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
  when: ansible_facts['distribution'] == "CentOS"

- name: Work out the distribution
  command: lsb_release -sc
  register: lsb_release_sc
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add repository (Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ lsb_release_sc.stdout }} stable"
    state: present
    filename: 'docker-ce'
    update_cache: true
  when: ansible_facts['distribution'] == "Ubuntu"


- import_tasks: install.yml
- import_tasks: enable.yml
- import_tasks: start.yml
