---

- import_tasks: install.yml


- name: Create the "{{ docker_app_db_user }}" user
  postgresql_user:
    name: '{{ docker_app_db_user }}'
    password: "{{ lookup('passwordstore', docker_app_name + '/' + docker_app_db_user + ' create=true')}}"
    encrypted: True
  no_log: True
#  become_user: postgres

- postgresql_db:
    name:  '{{ docker_app_db_name }}'
    owner: '{{ docker_app_db_user }}'
    state: present
    encoding: UTF-8
    template: template0
    lc_collate: 'ru_RU.UTF-8'
    lc_ctype:   'ru_RU.UTF-8'
 # become_user: postgres
