---

# the os packages

packages:
- ca-certificates
- curl
- python3
- gnupg

packages_CentOS:
- redhat-lsb-core
- glibc-langpack-ru
- glibc-locale-source

packages_Ubuntu:
- lsb-release
- language-pack-ru
